/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-04-25 14:53:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import Model.Bien;
import Model.Utilisateur;

public final class Catalogue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("Model.Utilisateur");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Model.Bien");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <link rel=\"icon\" href=\"../../../../favicon.ico\">\n");
      out.write("    <title>Page Catalogue</title>	\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n");
      out.write("    \n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body onload=\"cata\" class=\"bg-light\">\n");
      out.write("	");
 Utilisateur iduser = (Utilisateur) request.getAttribute("iduser"); 
      out.write("\n");
      out.write("    <header>      \n");
      out.write("      <div class=\"navbar p-3 navbar-dark bg-dark box-shadow\">\n");
      out.write("        <div class=\"container d-flex justify-content-between\">\n");
      out.write("          <a href=\"cata\" class=\"navbar-brand d-flex align-items-center\">\n");
      out.write("            <strong>Catalogue des biens</strong>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"affichecommande\" class=\"navbar-brand d-flex align-items-right\">\n");
      out.write("            <strong>Liste de Commande</strong>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"profile\" class=\"navbar-brand d-flex align-items-right\">\n");
      out.write("            <strong>Gere profile</strong>\n");
      out.write("          </a>\n");
      out.write("          <div>\n");
      out.write("          	<p class=\"text-white fs-2\">Welcome ");
      out.print( iduser.getNom() );
      out.write(' ');
      out.print( iduser.getPrenom() );
      out.write("</p>\n");
      out.write("          	<a class=\"fs-4\" href=\"deconnexion\">Deconnexion</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    <main role=\"main\">			\n");
      out.write("    <section class=\"jumbotron text-center mt-3 mb-4\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("         <h1 class=\"jumbotron-heading\">Nous Produits</h1>\n");
      out.write("      <div class=\"input-group mt-4\">\n");
      out.write("		 <div class=\"form-outline w-100\" data-mdb-input-init>\n");
      out.write("			<form action=\"search\" method=\"get\">\n");
      out.write("				<input placeholder=\"rechercher un produit depuis (prix or type)\" type=\"search\" name=\"recherche\" class=\"form-control p-4\" />\n");
      out.write("	         	<input type=\"submit\" value=\"rechercher\">\n");
      out.write("	        </form>\n");
      out.write("         </div>\n");
      out.write("      </div>	\n");
      out.write("     </div>     	\n");
      out.write("    </section>\n");
      out.write("    	\n");
      out.write("      <div  class=\"album py-5 bg-light\">\n");
      out.write("        <div class=\"container \" style=\"border:solid 5px grey;\">\n");
      out.write("          <div class=\"row mt-3\">          	\n");
      out.write("          	");
          	
          		List<Bien> listeBiens = (List<Bien>) request.getAttribute("liste");          		
          		
          		if (listeBiens.isEmpty()){
          			
      out.write("<h3>Aucun produit trouvé</h3>");
 
          		}          		
          		else{
	    		 for(Bien b : listeBiens){ 	    			 
    		
      out.write("\n");
      out.write("            <div class=\"col-md-4 \">\n");
      out.write("              <div class=\"card mb-4 box-shadow\">\n");
      out.write("                <img class=\"card-img-top\" src=\"");
      out.print( b.getImage() );
      out.write("\" alt=\"Card image cap\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <p class=\"card-text\">Type : <span class=\"text-success fw-bold\">");
      out.print( b.getType() );
      out.write("</span></p>	\n");
      out.write("                  <p class=\"card-text\">Description :<span class=\"text-dark fw-bold\"> ");
      out.print( b.getDescription() );
      out.write(" </span></p>\n");
      out.write("                  <p class=\"card-text\">Disponibilité : <span class=\"text-success fw-bold\">");
      out.print( b.getDisponibilite() );
      out.write("</span></p>\n");
      out.write("                  <p class=\"card-text\">Prix : <span class=\"text-dark fw-bold\">");
      out.print( b.getPrixParJour() );
      out.write("</span> DT</p>\n");
      out.write("                  <div class=\"d-flex justify-content-between align-items-center\">\n");
      out.write("                    <div class=\"btn-group w-100\">\n");
      out.write("                      <form name=\"f2\" action=\"reservation\" method=\"get\">\n");
      out.write("                      	<input type=\"hidden\" name=\"bienID\" value=\"");
      out.print( b.getId_bein());
      out.write("\">\n");
      out.write("                      	<input type=\"hidden\" name=\"iduser\" value=\"");
      out.print( iduser.getId());
      out.write("\">                        	                  	                     	\n");
      out.write("                      	<button type=\"submit\" class=\"btn btn-sm btn-outline-secondary text-dark\">Commander</button>\n");
      out.write("                      </form>\n");
      out.write("                    </div>                    \n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div> \n");
      out.write("            ");
 }} 
      out.write("             \n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </main>\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\n");
      out.write(" 	<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\n");
      out.write("    \n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
