/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-04-25 14:46:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Model.Bien;
import Model.Utilisateur;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Model.Utilisateur");
    _jspx_imports_classes.add("Model.Bien");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" <header>      \n");
      out.write("      <div class=\"navbar p-3 navbar-dark bg-dark box-shadow\">\n");
      out.write("        <div class=\"container d-flex justify-content-between\">\n");
      out.write("          <a href=\"cata\" class=\"navbar-brand d-flex align-items-left\">\n");
      out.write("            <strong>Catalogue des biens</strong>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"affichecommande\" class=\"navbar-brand d-flex align-items-right\">\n");
      out.write("            <strong>Liste de Commande</strong>\n");
      out.write("          </a>\n");
      out.write("          <a href=\"profile\" class=\"navbar-brand d-flex align-items-right\">\n");
      out.write("            <strong>Gere profile</strong>\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("    ");

    	Utilisateur user = (Utilisateur) request.getAttribute("user"); 
    	Bien b = (Bien) request.getAttribute("bien"); 
    
    
    
      out.write("\n");
      out.write("    \n");
      out.write("	<div class=\"container p-0 mt-3\">\n");
      out.write("	\n");
      out.write("        <div class=\"card px-4\">\n");
      out.write("        <p class=\"fs-2 fw-bold\" >C.Info : ");
      out.print( b.getDescription() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( b.getType() );
      out.write("</p>\n");
      out.write("            <p class=\"h8 py-3 fs-4\">Payer</p>\n");
      out.write("            <div class=\"row gx-3\">\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                <form action=\"makePayment\" method=\"get\">\n");
      out.write("                    <div class=\"d-flex flex-column\">\n");
      out.write("                        <p class=\"text mb-1\">Card Name</p>\n");
      out.write("                        <input class=\"form-control mb-3\" type=\"text\" placeholder=\"Name\" value=\"");
      out.print( user.getNom() );
      out.write(' ');
      out.print( user.getPrenom());
      out.write("\" required>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-12\">\n");
      out.write("                    <div class=\"d-flex flex-column\">\n");
      out.write("                        <p class=\"text mb-1\">Card Number</p>\n");
      out.write("                        <input class=\"form-control mb-3\" type=\"text\" placeholder=\"1234 5678 435678\"required>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-6\">\n");
      out.write("                    <div class=\"d-flex flex-column\">\n");
      out.write("                        <p class=\"text mb-1\">Expiry</p>\n");
      out.write("                        <input class=\"form-control mb-3\" type=\"text\" placeholder=\"MM/YYYY\" required>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-6\">\n");
      out.write("                    <div class=\"d-flex flex-column\">\n");
      out.write("                        <p class=\"text mb-1\">CVV/CVC</p>\n");
      out.write("                        <input class=\"form-control mb-3 pt-2 \" type=\"password\" placeholder=\"***\"required>\n");
      out.write("                    </div>\n");
      out.write("                </div>                \n");
      out.write("	                <input type=\"hidden\" name=\"idbien\" value=\"");
      out.print( b.getId_bein() );
      out.write("\">\n");
      out.write("	                <input type=\"hidden\" name=\"iduser\" value=\"");
      out.print( user.getId() );
      out.write("\">\n");
      out.write("	                <div>\n");
      out.write("	                    <button style=\"width:100%;\" class=\"btn btn-primary mb-3\">Payer | ");
      out.print( b.getPrixParJour() );
      out.write("DT</button>\n");
      out.write("	                </div>\n");
      out.write("                </form>                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
